export const chordInfo: { [key: string]: { frets: (number | null)[]; theory: string } } = {
  "C": { "frets": [null, 3, 2, 0, 1, 0], "theory": "Major Triad" },
  "Cmaj7": { "frets": [null, 3, 2, 0, 0, 0], "theory": "Major 7th" },
  "C7": { "frets": [null, 3, 2, 3, 1, 0], "theory": "Dominant 7th" },
  "Cm": { "frets": [null, 3, 5, 5, 4, 3], "theory": "Minor Triad" },
  "Cm7": { "frets": [null, 3, 5, 3, 4, 3], "theory": "Minor 7th" },
  "C#dim": { "frets": [null, 4, 5, 3, 5, null], "theory": "Diminished" },
  "D": { "frets": [null, null, 0, 2, 3, 2], "theory": "Major Triad" },
  "Dmaj7": { "frets": [null, null, 0, 2, 2, 2], "theory": "Major 7th" },
  "D7": { "frets": [null, null, 0, 2, 1, 2], "theory": "Dominant 7th" },
  "Dm": { "frets": [null, null, 0, 2, 3, 1], "theory": "Minor Triad" },
  "Dm7": { "frets": [null, null, 0, 2, 1, 1], "theory": "Minor 7th" },
  "E": { "frets": [0, 2, 2, 1, 0, 0], "theory": "Major Triad" },
  "Emaj7": { "frets": [0, 2, 1, 1, 0, 0], "theory": "Major 7th" },
  "E7": { "frets": [0, 2, 0, 1, 0, 0], "theory": "Dominant 7th" },
  "Em": { "frets": [0, 2, 2, 0, 0, 0], "theory": "Minor Triad" },
  "Em7": { "frets": [0, 2, 2, 0, 3, 0], "theory": "Minor 7th" },
  "F": { "frets": [1, 3, 3, 2, 1, 1], "theory": "Major Triad" },
  "Fmaj7": { "frets": [null, null, 3, 2, 1, 0], "theory": "Major 7th" },
  "Fm": { "frets": [1, 3, 3, 1, 1, 1], "theory": "Minor Triad" },
  "F#m7b5": { "frets": [2, null, 2, 2, 1, null], "theory": "Half-diminished" },
  "G": { "frets": [3, 2, 0, 0, 0, 3], "theory": "Major Triad" },
  "Gmaj7": { "frets": [3, null, 4, 4, 3, null], "theory": "Major 7th" },
  "G7": { "frets": [3, 2, 0, 0, 0, 1], "theory": "Dominant 7th" },
  "A": { "frets": [null, 0, 2, 2, 2, 0], "theory": "Major Triad" },
  "Amaj7": { "frets": [null, 0, 2, 1, 2, 0], "theory": "Major 7th" },
  "A7": { "frets": [null, 0, 2, 0, 2, 0], "theory": "Dominant 7th" },
  "Am": { "frets": [null, 0, 2, 2, 1, 0], "theory": "Minor Triad" },
  "Am7": { "frets": [null, 0, 2, 0, 1, 0], "theory": "Minor 7th" },
  "B": { "frets": [null, 2, 4, 4, 4, 2], "theory": "Major Triad" },
  "B7": { "frets": [null, 2, 1, 2, 0, 2], "theory": "Dominant 7th" },
  "Bm": { "frets": [null, 2, 4, 4, 3, 2], "theory": "Minor Triad" },
  "Bm7": { "frets": [null, 2, 4, 2, 3, 2], "theory": "Minor 7th" },
  "Bm7b5": { "frets": [null, 2, 3, 2, 3, null], "theory": "Half-diminished" }
}